
apiVersion: v1
kind: Pod
metadata:
 name: multi-pod2
 labels:
  author: sonal
  type: webserver
spec:
 containers:
 - name: c1
   image: nginx
 - name: c2
   image: tomcat
 - name: c3
   image: ubuntu
   command: ["bash", "-c", "sleep 6000"]
